---
title: "readme"
author: "Peter Searle"
date: "2023-04-18"
output: html_document
---

# Files used for differential expression analysis

Description: 

sample_info - Information of which RNA-seq files go with which week for Salmon analysis. When the files are downloaded from NCBI, they need to be renamed to match the names in these files. 
  june_samples.txt - June sucker
  straw_samples.txt - Strawberry Reservoir Utah sucker
  utah_samples.txt - Utah Lake Utah sucker

transcriptomes > unfiltered
  june_transcripts.fasta.gz - June sucker
  straw_transcripts.fasta.gz - Strawberry Reservoir Utah sucker
  utah_transcripts.fasta.gz - Utah Lake Utah sucker

The assembled transcriptomes on NCBI are slightly different than the assembled transcriptomes available in this repository. NCBI required several changes (i.e., removal of sequences < 200 bp and UniVec vector removal) to the original files. Using both files produces very similar results. However, to be consistent with what is shown in the manuscript, I use the original transcriptomes before they were processed by NCBI. The files need to be unzipped before running the analyses.

NCBI processed transcriptomes and RNA-Seq data is available on NCBI under accession PRJNA818778. Refer to ~/transcriptome_assembly/data/Genetic_Samples.xlsx for additional information on which samples are associated with which week and species.